USE ROLE SF_INTELLIGENCE_DEMO;
USE WAREHOUSE APP_WH;

CREATE OR REPLACE SEMANTIC VIEW COCO_DEMO.ANALYTICS.CUSTOMER_ANALYTICS_SV
  TABLES (
    cs AS COCO_DEMO.ANALYTICS.CUSTOMER_SUMMARY
      PRIMARY KEY (customer_id)
      COMMENT = 'One row per customer with aggregated order metrics'
  )
  DIMENSIONS (
    cs.customer_id AS cs.customer_id
      COMMENT = 'Unique identifier for each customer',
    cs.customer_name AS cs.customer_name
      COMMENT = 'Full name of the customer',
    cs.region AS cs.region
      WITH SYNONYMS = ('geography', 'area')
      COMMENT = 'Geographic region where the customer is located',
    cs.signup_date AS cs.signup_date
      COMMENT = 'Date the customer first registered',
    cs.first_order_date AS cs.first_order_date
      COMMENT = 'Date of the customers earliest order',
    cs.last_order_date AS cs.last_order_date
      COMMENT = 'Date of the customers most recent order'
  )
  METRICS (
    cs.total_orders AS SUM(cs.total_orders)
      WITH SYNONYMS = ('order count', 'number of orders')
      COMMENT = 'Total number of orders placed by the customer',
    cs.total_revenue AS SUM(cs.total_revenue)
      WITH SYNONYMS = ('revenue', 'sales', 'total sales')
      COMMENT = 'Total revenue generated by the customer across all orders',
    cs.avg_order_value AS AVG(cs.avg_order_value)
      WITH SYNONYMS = ('average order', 'aov')
      COMMENT = 'Average dollar amount per order for the customer',
    cs.days_since_last_order AS AVG(cs.days_since_last_order)
      WITH SYNONYMS = ('recency', 'days inactive')
      COMMENT = 'Number of days since the customers most recent order'
  )
  COMMENT = 'Customer analytics semantic view for Cortex Analyst providing customer-level order metrics and dimensions';
